### PR TITLE
Fix tests for 208

### PR DESCRIPTION
**Pull request by jmcarp**
Fix incompatibility with MongoDB / pymongo (slight modification from #208) and update broken tests.

### CODE REVIEW

**Comment by thedrow** [comment]
Oh I really need this one.
HTTPretty hangs my tests because of my use of pymongo.

**Comment by thedrow** [comment]
I just tested this patch and it solves my issue. Please merge and release.

**Comment by sloria** [comment]
+1

**Comment by thedrow** [comment]
@jmcarp I'm currently using your fork so don't delete this branch after this is merged.

**Comment by thedrow** [comment]
@gabrielfalcao Can you please merge and release?

**Comment by gabrielfalcao** [comment]
HTTPretty 0.8.8 released with this

**Comment by gabrielfalcao** [comment]
sorry for not seeing this before

**Comment by thedrow** [comment]
:claps:

**Pull request merged**
