### PR TITLE
Fix py34 hanging

### PR DESCRIPTION
**Pull request by bpicolo**
This solves #228. Not 100% sure what causes the issue in py34 vs others .It's not entirely clear why it only occurs in 3.4. Will try to make a minimal repro test case. -_-. This was changed in #216

### CODE REVIEW

**Comment by bpicolo** [comment]
Looks like some bizarre shadowing of "type" is going on in 3.4, which is probably the root cause. Still trying to figure out how the heck it happens. Haven't been able to repro this in a smaller case. Happens in _socket -_-

```
-> if httpretty.allow_net_connect
> /usr/lib64/python3.4/socket.py(124)__init__()
-> self._io_refs = 0
(Pdb) self.type

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<httpretty.core.fakesock.socket object at 0x7f8e02738cc0>
(Pdb) type
1
(Pdb) __builtins__['type'](self)
<class 'socket.socket'>

```

**Comment by bpicolo** [comment]
https://bugs.python.org/issue20386

Nice, in some version of py3 SocketType refers to a different thing. Will add this to fix.

**Comment by bpicolo** [comment]
@gabrielfalcao  Take a look at this when you have a chance? : )

**Comment by gabrielfalcao** [comment]
That's great @bpicolo, I just merged!

**Comment by gabrielfalcao** [comment]
HTTPretty 0.8.10 was released with this fix

**Pull request merged**
