### PR TITLE
WIP solution for TypeError: wrap_socket() missing 1 required positional argument: 'sock'

### LINKED ISSUE #345: TypeError: wrap_socket() missing 1 required positional argument: 'sock'
I am getting this error since the release of `0.9.5`. This happens on Python 2.7, 3.4, 3.5 and 3.6.

Here's the stack-trace:
```
Traceback (most recent call last):
  File "/home/travis/build/GetStream/stream-django/.eggs/httpretty-0.9.5-py3.6.egg/httpretty/core.py", line 1636, in wrapper
    return test(*args, **kw)
  File "/home/travis/build/GetStream/stream-django/stream_django/tests/test_app/tests/test_manager.py", line 48, in test_unfollow_user
    feed_manager.unfollow_user(1, 2)
  File "/home/travis/build/GetStream/stream-django/stream_django/managers.py", line 49, in unfollow_user
    feed.unfollow(target_feed.slug, target_feed.user_id)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/stream/feed.py", line 166, in unfollow
    response = self.client.delete(url, signature=token, params=params)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/stream/client.py", line 271, in delete
    return self._make_request(self.session.delete, *args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/stream/client.py", line 210, in _make_request
    params=default_params, timeout=self.timeout)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 591, in delete
    return self.request('DELETE', url, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/home/travis/build/GetStream/stream-django/.eggs/httpretty-0.9.5-py3.6.egg/httpretty/core.py", line 600, in fake_wrap_socket
    return orig_wrap_socket_fn(*args, **kw)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/travis/build/GetStream/stream-django/.eggs/httpretty-0.9.5-py3.6.egg/httpretty/core.py", line 600, in fake_wrap_socket
    return orig_wrap_socket_fn(*args, **kw)
TypeError: wrap_socket() missing 1 required positional argument: 'sock'
```

This is happening on a public Github project during Travis (https://travis-ci.org/GetStream/stream-django/builds).

### PR DESCRIPTION
**Pull request by gabrielfalcao**
takes code from #290

closes #345
closes #290

### CODE REVIEW

**Comment by nicolasmota** [comment]
I'm interested in this fix. Do you have any idea when the release will be posted?

**Comment by gabrielfalcao** [comment]
Hopefully tomorrow 🙏

**Comment by nicolasmota** [comment]
nice! I'll wait.

**Comment by gabrielfalcao** [comment]
> nice! I'll wait.

https://pypi.org/project/httpretty/1.0.0/

**Pull request merged**
