### PR TITLE
add httpretty.has_request() and test

### PR DESCRIPTION
**Pull request by jimabramson**
@gabrielfalcao thanks for providing this useful library.

In many of the tests I write I want there to be a simple, readable API for determining whether or not any request was actually captured.  This PR adds one method to do that.

### CODE REVIEW

**Comment by gabrielfalcao** [comment]
What a beautiful patch: simple functionality + unit test. Perfect package!

**Comment by gabrielfalcao** [comment]
I'll merge and release as soon as the build passes

**Comment by gabrielfalcao** [comment]
hey @jimabramson this is so great, I'll merge and make a release, but I would love to have this new method added to the README/documentation so that everybody can benefit from it.

I might not have time to do it today, but if you have extra time and wants to give some love to the README file I will certainly merge and release right away.

Cheers!

**Comment by jimabramson** [comment]
@gabrielfalcao  I am happy to take a swing at the README, will follow up with a second commit in a little while.

**Comment by gabrielfalcao** [comment]
:heart:

**Comment by jimabramson** [comment]
@gabrielfalcao I amended the original commit with an example for docs.  It seems that the three files I updated have (mostly) the same content so I followed that pattern.  Let me know if this fits the conventions.

**Comment by gabrielfalcao** [comment]
Hey @jimabramson sorry for the delay, I got sidetracked this weekend. Merging now

**Comment by gabrielfalcao** [comment]
Releasing `0.8.9`

**Comment by gabrielfalcao** [comment]
https://pypi.python.org/pypi/httpretty/0.8.9

**Comment by jimabramson** [comment]
thanks @gabrielfalcao !

**Pull request merged**
